[package]
name = "rust_web"
version = "0.1.0"
edition = "2021"

[dependencies]
opentelemetry = { version = "0.29.1", features = ["metrics"] }
opentelemetry_sdk = { version = "0.29.0", features = ["metrics", "rt-tokio"] }
opentelemetry-otlp = { version = "0.29.0", features = ["metrics", "grpc-tonic"] }
tonic = { version = "0.11", features = ["tls", "tls-roots"] }
tokio = { version = "1.45.0", features = ["full"] }
axum = { version = "0.7", features = ["tokio", "http1"] }
